package com.zqb.mvvmkotlin.model.bean

/**
 *创建时间:2019/4/17 18:34
 */
data class ImageData(
    val globalQC: Any,
    val hintWords: List<String>,
    val isClusterfilter: Boolean,
    val isForbiden: Any,
    val isPornQuery: Int,
    val isQcResult: String,
    val isTinyQcNull: Boolean,
    val items: ArrayList<Item>,
    val itemsOnPage: Int,
    val maxEnd: Int,
    val query: String,
    val refineQuery: String,
    val refineQueryEncode: String,
    val showFiltered: Boolean,
    val startIndex: Int,
    val tc: String,
    val totalItems: String,
    val ts: String,
    val uuid: String
) {
    data class Item(
        val allSummary: Boolean,
        val alt: Any,
        val anchor: Any,
        val anchor1: Any,
        val base_url: String,
        val cacheIndex: Int,
        val dataType: String,
        val date: Any,
        val debugInfo: Any,
        val docid: String,
        val downloadNum: Any,
        val downloadPath: Any,
        val easter: Boolean,
        val easterUrl: Any,
        val encoding: Any,
        val fastSummary: Boolean,
        val feeddata: Any,
        val gifdata: Any,
        val groupid: Any,
        val groupsize: Int,
        val grpdata: Any,
        val grpdocs: Any,
        val height: String,
        val hittag: String,
        val imgcolor: String,
        val imgkey1: String,
        val imgkey2: String,
        val lastmodified: String,
        val ldata: String,
        val markedSummary: Any,
        val markedTitle: String,
        val mf_id: String,
        val normalSummary: Boolean,
        val oriTitle: String,
        val ori_pic_url: String,
        val page_url: String,
        val pic_url: String,
        val pic_url_noredirect: String,
        val pptdata: Any,
        val showSnapShot: Boolean,
        val simdata: List<Any>,
        val similarUrlFirst: Any,
        val similarUrlSecond: Any,
        val siteName: Any,
        val size: String,
        val smallThumbUrl: String,
        val sohu_image: String,
        val speedrank: Any,
        val summary: Any,
        val summarypc: String,
        val summarytype: String,
        val surr1: Any,
        val surr2: String,
        val thumbUrl: String,
        val thumb_height: String,
        val thumb_width: String,
        val time: Int,
        val title: String,
        val title1: String,
        val title2: Any,
        val type: Int,
        val uri: String,
        val url: Any,
        val width: String
    )

}
